bean_dev_tool:
    library_source: E:\wamp31\www\libraries\swarranty\
    library_workspace: E:\wamp31\www\swarranty\system\libraries\
    components: ~
    bundles:
        - MagentaSWarrantyModelBundle
        - MagentaSWarrantyAdminBundle