bean_dev_tool:
    library_source: D:\workspace\libraries\swarranty\
    library_workspace: D:\workspace\magenta\swarranty\system\libraries\
    components: ~
    bundles:
        - MagentaSWarrantyModelBundle
        - MagentaSWarrantyAdminBundle